name: Daily getter

on:
  schedule:
    - cron: '0 2,18 * * *' # Runs daily at 02:00 and 18:00 UTC
  workflow_dispatch: # Allows manual run from GitHub Actions UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required to push to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Run getter
        run: python main.py

      - name: Force-push single commit to dedicated branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout --orphan data
          git reset
          git add data.json
          git commit -m "chore: automated product data update"
          git push origin data --force
